"""Versioned host compatibility preconditions, separate from portable semantics."""

# Order is the historical host recipe, not a claim that every step is a
# mathematical prerequisite of every following rule. Explicit predicates and
# imported helpers below define the real adapter dependencies.
COMPATIBILITY_CONTRACTS = {
 'static': dict(kind='root_static_controls',predicate='Fixed graph ABI; shape/control expressions proven constant; ReduceProd int64 exact; Concat only proven empty operands.',hard_dependencies=['shape_dataflow.py'],source_scope='Generic static identities implemented for CPU conversion; exported logical source already has bound shape controls.',target_policy='Keep valid root proof, apply only needed control binding/folding; no inference-data constants.'),
 'dcn': dict(kind='cpu_rank_limit',predicate='DCN Reshape→rank6 Transpose→Reshape, exclusive intermediates, rank<=4 final and exact permutation.',hard_dependencies=['shape_dataflow.py'],source_scope='Matcher uses /deform_conv/ names plus full shape/permutation/consumer guards; CPU adapter.',target_policy='Skip when native backend supports source rank; do not require extra CPU shuffles in portable graph.'),
 'singleton': dict(kind='cpu_rank_limit',predicate='Internal scoped seg_head/motion-root rank6 leading singleton; supported axes preserve singleton; no public rank change.',hard_dependencies=['shape_dataflow.py'],source_scope='Scope names and leading singleton are adapter preconditions, independent of DCN math.',target_policy='Optional backend rank adapter; retain all source integer/bool/axis contracts.'),
 'packed': dict(kind='cpu_rank_limit',predicate='Internal rank>5 tensors or rank5 Transpose; supported operations only; adjacent axes grouped by identical broadcasting; signed32 scatter address range.',hard_dependencies=['shape_dataflow.py','lower_transpose.py'],source_scope='Aliases /qnn_packed are CPU physical representation; preserve logical source identity.',target_policy='Replace/skip by backend rank/capability profile; no public capacity or precision change.'),
 'protected': dict(kind='cpu_pattern_guard',predicate='Reshape rank<2→rank5; pure [1,count] rank2 view before target; exact element order.',hard_dependencies=['shape_dataflow.py'],source_scope='Shape produced by prior adapter may create/remove matches; not an arithmetic dependency.',target_policy='Only retain for a backend with the observed reshape validator restriction.'),
 'ports': dict(kind='cpu_wire_abi',predicate='Scalar public ports become one-element native ports with internal scalar views; names/dtypes/int bits preserved.',hard_dependencies=[],source_scope='Explicit logical↔native ABI adapter; never silently reinterpret a physical layout.',target_policy='Replace by target scalar/typed IO ABI; generic public logical scalar contract unchanged.'),
 'tile': dict(kind='cpu_broadcast_adapter',predicate='Expand is root-proven broadcast, repetitions integral; pure index order; scalar uses Identity.',hard_dependencies=['shape_dataflow.py'],source_scope='Optional equivalent CPU converter expression; Tile may physically materialize data.',target_policy='Prefer native broadcast/fusion when supported; keep materialization differences visible.'),
 'broadcast': dict(kind='cpu_layout_broadcast_adapter',predicate='Named encoder deformable-attention Mul_8; shapes [B,C,Q,P] and [B,1,Q,P]; adjacent Q/P grouped to rank3.',hard_dependencies=['shape_dataflow.py','lower_rank.py'],source_scope='Original operand semantics survive; historical name matcher stays within adapter. New portable attention_regions accepts raw or packed structure.',target_policy='Keep standard Mul/shape semantics in portable layer; select rank3 only where needed.'),
 'boolean': dict(kind='cpu_dtype_adapter',predicate='Bool Concat/Slice data-only operands; exact bool↔int32 0/1 casts and restoration.',hard_dependencies=['shape_dataflow.py'],source_scope='CPU routing limitation, no mask semantics or dtype widening in public ABI.',target_policy='Use native bool routing if supported; otherwise explicit exact adapter.'),
 'scatter': dict(kind='cpu_index_adapter',predicate='Root-constant negative Gather/ScatterND indices in valid [-extent,extent) bounds; per-node normalization.',hard_dependencies=['shape_dataflow.py'],source_scope='No runtime-input constant folding or float index arithmetic.',target_policy='Backend index policy adapter; exact source negative-coordinate semantics retained.'),
 'reduction': dict(kind='cpu_integer_operator_adapter',predicate='__q3_sca_max int64 [6] ReduceMax→scalar, axes[0], keepdims0; Gather/Greater/Where and scalar views.',hard_dependencies=['shape_dataflow.py'],source_scope='Explicit SCA source-semantic anchor; integer routing adapter, not tensor-name heuristic alone.',target_policy='Keep native integer ReduceMax where supported, otherwise exact comparison/select adapter.'),
 'root-extents': dict(kind='root_static_controls',predicate='Shape/Size of proven extents only; outputs constant and exact; no dependence on runtime tensor values.',hard_dependencies=['shape_dataflow.py'],source_scope='Generic extent proof/simplification also useful outside CPU; cannot fold data-dependent geometry.',target_policy='Reusable root-only rule, applied on each graph identity.'),
 'integer-clip': dict(kind='cpu_integer_operator_adapter',predicate='int32/int64 Clip; scalar same-type constant bounds valid and ordered; integer Less/Greater/Where.',hard_dependencies=['shape_dataflow.py'],source_scope='Preserve all integer bits, capacity and validity; no narrowing/float casts.',target_policy='Native integer Clip or equivalent exact target adapter.'),
 'integer-scatter': dict(kind='cpu_integer_operator_adapter',predicate='int32/int64 rank1 ScatterND; root constant [1,1] coordinate; one update, no reduction; exact Slice/Concat.',hard_dependencies=['shape_dataflow.py'],source_scope='Only proven single-position routing, not arbitrary dynamic scatter.',target_policy='Native ScatterND when suitable; otherwise this bounded semantic adapter.'),
 'gather-elements': dict(kind='cpu_rank_limit',predicate='GatherElements rank5; gather axis<3, equal trailing non-gather extents, root-proven positive dimensions.',hard_dependencies=['shape_dataflow.py'],source_scope='Pure equal-trailing packing plus native GatherElements and restore.',target_policy='Re-evaluate target rank/operator support; preserve negative-index and exact-bit data routing.'),
}

LIFECYCLE_CONTRACT = dict(schema='portable-graph-resource-lifecycle-v1',
 resource_key=['logical_graph_sha256','compiled_graph_sha256','ordered_native_abi_sha256','backend_library_sha256','bridge_sha256','backend_profile_sha256','resource_epoch'],
 operations=['prepare_bind','execute','reset_state','invalidate_resources','close'],
 state_reset='Clear recurrent scene state without implicitly destroying compatible immutable graph resources.',
 ownership='Synchronous borrowed input remains stable until return; retained output owns its storage and survives later calls/evictions/close.',
 invalidation='Changed resource key rejects reuse; failure releases affected context, no partial state commit; next valid call rebuilds safely.',
 budgets=['retained_context_count','estimated_context_and_scratch_bytes','observed_peak_rss','shared_buffers','retained_returned_outputs'],
 observations=['prepare_count','finalize_count','cache_hit','cache_miss','eviction','retained_count','retained_estimated_bytes','prepare_seconds','execute_seconds'],
 cyclic_control='Bounded sequential traversal across at least 2-3 cycles must expose thrashing; one hot-context second execution is insufficient.',
 backend_unknown=['actual_device_scratch','context_binary_compatibility','memory_registration','synchronization','target_budget'],
 scope='Portable lifetime/ownership/identity contract. CPU implementation and device-context adapter are independent; no promise every graph is permanently resident.')
