#!/usr/bin/env python3
"""Bind an installed QAIRT SDK to one local Conda environment (WSL/Linux Bash)."""
import argparse
import json
import os
from pathlib import Path
import shlex
import sys


ACTIVATE = r'''# Generated by tools/install_sdk_hooks.py; local machine configuration.
_uniad_qairt_activate() {
    local sdk=@@SDK@@ prefix=@@PREFIX@@ key saved entry value root
    local -a roots entries
    roots=("${QAIRT_SDK:-}" "${QAIRT_SDK_ROOT:-}" "${QNN_SDK_ROOT:-}" "${SNPE_ROOT:-}")
    for key in QAIRT_SDK QAIRT_SDK_ROOT QNN_SDK_ROOT SNPE_ROOT HEXAGON_TOOLS_DIR QNN_CONVERTER_ENV PYTHONPATH LD_LIBRARY_PATH Q4_QAIRT_SDK Q4_CONVERTER_ENV; do
        saved="_UNIAD_QAIRT_SAVED_${key}"
        printf -v "${saved}_SET" '%s' "${!key+x}"
        printf -v "$saved" '%s' "${!key-}"
    done
    # Conda owns PATH. SDK commands are environment-local links, so switching
    # environments cannot reintroduce an SDK bin directory from a cached PATH.
    for key in PATH PYTHONPATH LD_LIBRARY_PATH; do
        value=''
        IFS=: read -r -a entries <<< "${!key-}"
        for entry in "${entries[@]}"; do
            [[ -z "$entry" ]] && continue
            for root in "${roots[@]}"; do
                if [[ -n "$root" && "$entry" == "$root/"* ]]; then entry=''; break; fi
            done
            [[ -z "$entry" ]] || value="${value:+$value:}$entry"
        done
        printf -v "$key" '%s' "$value"
        export "$key"
    done
    export QAIRT_SDK="$sdk" QAIRT_SDK_ROOT="$sdk" QNN_SDK_ROOT="$sdk" SNPE_ROOT="$sdk"
    export QNN_CONVERTER_ENV="$prefix"
    export PYTHONPATH="$sdk/lib/python:$sdk/benchmarks/QNN${PYTHONPATH:+:$PYTHONPATH}"
    export LD_LIBRARY_PATH="$sdk/lib/x86_64-linux-clang${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    unset HEXAGON_TOOLS_DIR Q4_QAIRT_SDK Q4_CONVERTER_ENV
    if compgen -G "$sdk/bin/x86_64-linux-clang/hexagon-*" > /dev/null; then
        export HEXAGON_TOOLS_DIR="$sdk/bin/x86_64-linux-clang"
    fi
}
_uniad_qairt_activate
unset -f _uniad_qairt_activate
'''

DEACTIVATE = r'''# Generated by tools/install_sdk_hooks.py; restore values including unset/empty.
_uniad_qairt_deactivate() {
    local key saved marker
    for key in QAIRT_SDK QAIRT_SDK_ROOT QNN_SDK_ROOT SNPE_ROOT HEXAGON_TOOLS_DIR QNN_CONVERTER_ENV PYTHONPATH LD_LIBRARY_PATH Q4_QAIRT_SDK Q4_CONVERTER_ENV; do
        saved="_UNIAD_QAIRT_SAVED_${key}"; marker="${saved}_SET"
        if [[ "${!marker-}" == x ]]; then
            printf -v "$key" '%s' "${!saved-}"
            export "$key"
        else
            unset "$key"
        fi
        unset "$saved" "$marker"
    done
}
_uniad_qairt_deactivate
unset -f _uniad_qairt_deactivate
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sdk', type=Path, required=True)
    parser.add_argument('--conda-prefix', type=Path, default=os.environ.get('CONDA_PREFIX'))
    args = parser.parse_args()
    if args.conda_prefix is None:
        parser.error('Activate the intended Conda environment or supply --conda-prefix')
    sdk, prefix = args.sdk.expanduser().resolve(), args.conda_prefix.expanduser().resolve()
    tools = sdk / 'bin/x86_64-linux-clang'
    if not (prefix / 'conda-meta').is_dir() or not (prefix / 'bin/python').is_file():
        parser.error('The destination must be an existing Conda environment')
    if not (tools / 'qnn-net-run').is_file() or not (sdk / 'lib/python').is_dir():
        parser.error('SDK does not contain the required Linux host tools')
    hooks = prefix / 'etc/conda'
    state_path = hooks / 'uniad-qairt-sdk.json'
    previous = json.loads(state_path.read_text()) if state_path.exists() else {'tools': {}}
    links = {tool.name: str(tool) for tool in sorted(tools.iterdir())
             if tool.is_file() and os.access(tool, os.X_OK)}
    # Refuse to overwrite independently installed commands or hooks.
    for name in links:
        dest = prefix / 'bin' / name
        if dest.exists() or dest.is_symlink():
            owned = previous['tools'].get(name)
            if not dest.is_symlink() or str(dest.readlink()) != owned:
                parser.error('Existing command is not managed by this installer: ' + str(dest))
    for directory in ('activate.d', 'deactivate.d'):
        dest = hooks / directory / 'uniad-qairt-sdk.sh'
        if dest.exists() and not dest.read_text().startswith('# Generated by tools/install_sdk_hooks.py;'):
            parser.error('Existing hook is not managed by this installer: ' + str(dest))
    for name, target in previous['tools'].items():
        dest = prefix / 'bin' / name
        if dest.is_symlink() and str(dest.readlink()) == target:
            dest.unlink()
    for name, target in links.items():
        (prefix / 'bin' / name).symlink_to(target)
    for directory, text in [('activate.d', ACTIVATE), ('deactivate.d', DEACTIVATE)]:
        dest = hooks / directory / 'uniad-qairt-sdk.sh'
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text.replace('@@SDK@@', shlex.quote(str(sdk))).replace('@@PREFIX@@', shlex.quote(str(prefix))))
    state_path.write_text(json.dumps(dict(sdk=str(sdk), prefix=str(prefix), tools=links), indent=2) + '\n')
    print(json.dumps(dict(status='installed', sdk=str(sdk), conda_prefix=str(prefix),
                          linked_commands=len(links), next_step='Deactivate and reactivate this environment'), indent=2))


if __name__ == '__main__':
    main()
